name: Test

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Choose an workflow"
        required: true
        default: "test"
        type: choice
        options:
          - test
          - build
  # push:
  #   branches: [main]

jobs:
  test:
    if: github.event.inputs.task == 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Pull Images
        run: |
          podman pull debian
          podman pull ubuntu
          podman pull archlinux
      - name: Podman Login
        uses: redhat-actions/podman-login@v1
        with:
          username: cnb
          password: ${{ secrets.CNB_TOKEN }}
          registry: docker.cnb.cool
      - name: cnb
        run: |
          cnb_url="docker.cnb.cool"
          # Debian
          podman tag debian $cnb_url/cnb-docker/docker/debian:latest
          podman push $cnb_url/cnb-docker/docker/debian:latest
          # Ubuntu
          podman tag ubuntu $cnb_url/cnb-docker/docker/ubuntu:latest
          podman push $cnb_url/cnb-docker/docker/ubuntu:latest
          # Arch Linux
          podman tag archlinux $cnb_url/cnb-docker/docker/archlinux:latest
          podman push $cnb_url/cnb-docker/docker/archlinux:latest

  build_images:
    if: github.event.inputs.task == 'build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Test
        uses: docker/build-push-action@v6
        with:
          context: ./texlive
          platforms: amd64
          push: true
          # tags: "chanzz0/texlive:${{ github.event.inputs.DOCKER_TAG }}"
          tags: "chanzz0/texlive:${{ env.TL_TEST }}"
